spring:
  application:
    name: crud
  thymeleaf:
    enabled: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/crud?useUnicode=yes&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
server:
  port: 8080