name: Build and Deploy Spring Boot Employees CRUD App - Huda Arqib

on:
  push:
    branches: [ main ]  # Change to your branch name if needed
  pull_request:
    branches: [ main ]  # Change to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose other supported runners
    steps:
      - uses: actions/checkout@v3  # Checkout code from your repository
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Adjust if you use a different Java version
          caches: maven  # Cache Maven packages to speed up builds
      - name: Build with Maven
        run: mvn package  # Replace with your build command if different

      - name: Archive JAR file (optional)
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app.jar
          path: target/*.jar  # Adjust path if your JAR file is located elsewhere
